AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for IAM Scanner roles
Outputs: 
  LambdaRoleArn:
    Description: Lambda IAM Scanner Role ARN
    Value:
      Fn::GetAtt: [LambdaRole, Arn]
Parameters:
  LambdaRoleName:
    AllowedPattern: '[-_a-zA-Z0-9]+'
    Default: IAMScannerLambdaRole
    Description: Provide an role name for the Master Role. Maximum 64 characters allowed
    Type: String
    MaxLength: 64
    MinLength: 1
  LambdaName:
    AllowedPattern: '[-_a-zA-Z0-9]+'
    Default: IAMScanner
    Description: Provide the name for the Lambda Function to be created.
    Type: String
  MemberRoleName:
    AllowedPattern: '[-_a-zA-Z0-9]+'
    Default: IAMScannerMemberRole
    Description: Provide an role name for the Member Roles.
    Type: String
  SplunkSecretName:
    AllowedPattern: '[-_a-zA-Z0-9]+'
    Default: SplunkSecret
    Description: Provide the Name of the secret that provides access to make requests to Splunk.
    Type: String
  DeploymentMode:
    Type: String
    Default: "Organization"
    AllowedValues:
      - "Organization"
      - "Single Account"
    Description: "Choose if the deployment of Fargate Defender will be across the organization or a only this account"
  OrganizationalUnitIds:
    Description: Provide the organizational root OU ID (Prefix like r-) if you want to run it for all the accounts under this Organization. Else provide a comma-separated list of OU ids(Prefix like ou-).
    Type: CommaDelimitedList
Conditions:
  IsOrgDeployment:
    Fn::Equals:
      - 
        Ref: DeploymentMode
      - "Organization"
Resources:
  IAMScannerLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: IAMScannerLambdaPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: GetOrgInfoAndGetSTSToken
          Effect: Allow
          Action:
          - "organizations:ListRoots"
          - "organizations:ListChildren"
          - "organizations:DescribeOrganizationalUnit"
          - "organizations:DescribeOrganization"
          - "organizations:DescribeAccount"
          - "sts:GetServiceBearerToken"
          Resource: "*"
        - Sid: STSAssumeRole
          Effect: Allow
          Action:
          - "sts:AssumeRole"
          Resource: 
            Fn::Sub:
              - "arn:aws:iam::*:role/${MemberRole}"
              - MemberRole:
                  Ref:
                    MemberRoleName
        - Sid: NetworkInterfaces
          Effect: Allow
          Action: 
          - "ec2:CreateNetworkInterface"
          - "ec2:DeleteNetworkInterface"
          - "ec2:DescribeNetworkInterfaces"
          Resource: "*"
        - Sid: LambdaLogsPermissions
          Effect: Allow
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Resource: "arn:aws:logs:*:*:*"
        - Sid: SplunkSecretAccess
          Effect: Allow
          Action:
          - "secretsmanager:GetSecretValue"
          Resource: 
            Fn::Sub: "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SplunkSecretName}-*"

  IAMScannerMemberPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: IAMScannerMemberPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: IAMPermissions
          Effect: Allow
          Action:
          - "iam:GetPolicy"
          - "iam:GetPolicyVersion"
          - "iam:ListAttachedUserPolicies"
          - "iam:ListAccessKeys"
          - "iam:ListUsers"
          Resource: "*"

  LambdaRole:
    Type: AWS::IAM::Role
    DependsOn:
    - IAMScannerLambdaPolicy
    Properties:
      RoleName: 
        Ref:
          LambdaRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: "lambda.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      ManagedPolicyArns:
      - Fn::GetAtt: [IAMScannerLambdaPolicy, PolicyArn]

  MemberRole:
    Type: AWS::IAM::Role
    DependsOn:
    - IAMScannerMemberPolicy
    - LambdaRole
    Properties:
      RoleName: 
        Ref:
          MemberRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Fn::GetAtt: [LambdaRole, Arn]
          Action:
          - "sts:AssumeRole"
      ManagedPolicyArns:
      - Fn::GetAtt: [IAMScannerMemberPolicy, PolicyArn]

  MemberRolesStackSet:
    Type: AWS::CloudFormation::StackSet
    Condition: IsOrgDeployment
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      OperationPreferences:
        FailureTolerancePercentage: 100
        RegionConcurrencyType: PARALLEL
      Parameters:
      - ParameterKey: MemberRoleName
        ParameterValue: 
          Ref: MemberRoleName
      - ParameterKey: LambdaRoleArn
        ParameterValue: 
          Fn::GetAtt: [LambdaRole, Arn]
      Capabilities:
      - CAPABILITY_NAMED_IAM
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds: 
            Ref: OrganizationalUnitIds
        Regions:
          - Ref: AWS::Region
      StackSetName:
        Ref: AWS::StackName
      TemplateBody: |
        {
          "AWSTemplateFormatVersion": "2010-09-09",
          "Description": "Stack for IAM roles for checking Admission Controller",
          "Parameters": {
            "LambdaRoleArn": {
              "AllowedPattern": "^arn:aws:iam::\\d{12}:role/[a-zA-Z0-9_.-]{1,64}$",
              "Description": "Provide an role name for the Master Role. Maximum 64 characters allowed",
              "Type": "String"
            },
            "MemberRoleName": {
              "AllowedPattern": "[-_a-zA-Z0-9]+",
              "Default": "IAMScannerMemberRole",
              "Description": "Provide an role name for the Member Roles. Maximum 64 characters allowed",
              "Type": "String",
              "MaxLength": 64,
              "MinLength": 1
            }
          },
          "Resources": {
            "IAMScannerMemberPolicy": {
              "Type": "AWS::IAM::ManagedPolicy",
              "Properties": {
                "ManagedPolicyName": "IAMScannerMemberPolicy",
                "PolicyDocument": {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Sid": "IAMPermissions",
                      "Effect": "Allow",
                      "Action": [
                        "iam:GetPolicy",
                        "iam:GetPolicyVersion",
                        "iam:ListAttachedUserPolicies",
                        "iam:ListAccessKeys",
                        "iam:ListUsers"
                      ],
                      "Resource": "*"
                    }
                  ]
                }
              }
            },
            "MemberRole": {
              "Type": "AWS::IAM::Role",
              "DependsOn": [
                "IAMScannerMemberPolicy"
              ],
              "Properties": {
                "RoleName": {
                  "Ref": "MemberRoleName"
                },
                "AssumeRolePolicyDocument": {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": {
                          "Ref": "LambdaRoleArn"
                        }
                      },
                      "Action": [
                        "sts:AssumeRole"
                      ]
                    }
                  ]
                },
                "ManagedPolicyArns": [
                  {
                    "Fn::GetAtt": [
                      "IAMScannerMemberPolicy",
                      "PolicyArn"
                    ]
                  }
                ]
              }
            }
          }
        }